# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/andy3/Desktop/NeuralNetwork/code/Basys3_Master.xdc

# IP: ip/blk_mem_gen_hidden_layer_weight_65x10/blk_mem_gen_hidden_layer_weight_65x10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_hidden_layer_weight_65x10 || ORIG_REF_NAME==blk_mem_gen_hidden_layer_weight_65x10} -quiet] -quiet

# IP: ip/blk_mem_gen_input_layer_weight_785x64/blk_mem_gen_input_layer_weight_785x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_input_layer_weight_785x64 || ORIG_REF_NAME==blk_mem_gen_input_layer_weight_785x64} -quiet] -quiet

# IP: ip/blk_mem_gen_input/blk_mem_gen_input.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_input || ORIG_REF_NAME==blk_mem_gen_input} -quiet] -quiet

# IP: ip/blk_mem_gen_canvas/blk_mem_gen_canvas.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_canvas || ORIG_REF_NAME==blk_mem_gen_canvas} -quiet] -quiet

# XDC: ip/blk_mem_gen_hidden_layer_weight_65x10/blk_mem_gen_hidden_layer_weight_65x10_ooc.xdc

# XDC: ip/blk_mem_gen_input_layer_weight_785x64/blk_mem_gen_input_layer_weight_785x64_ooc.xdc

# XDC: ip/blk_mem_gen_input/blk_mem_gen_input_ooc.xdc

# XDC: ip/blk_mem_gen_canvas/blk_mem_gen_canvas_ooc.xdc
