webtalk_init -webtalk_dir C:/Users/andy3/Desktop/NeuralNetwork/Neural_Network/Neural_Network.sim/sim_1/behav/xsim/xsim.dir/test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 14 03:16:58 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae60f6f8-683c-4033-b74b-bc9800e57ee3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4820692141754ab49a557176b23600ae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "105" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1581737 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16648_KB" -context "xsim\\usage"
webtalk_transmit -clientid 127497667 -regid "" -xml C:/Users/andy3/Desktop/NeuralNetwork/Neural_Network/Neural_Network.sim/sim_1/behav/xsim/xsim.dir/test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/andy3/Desktop/NeuralNetwork/Neural_Network/Neural_Network.sim/sim_1/behav/xsim/xsim.dir/test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/andy3/Desktop/NeuralNetwork/Neural_Network/Neural_Network.sim/sim_1/behav/xsim/xsim.dir/test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
